version: "3.8"
services:
  tempus-hub:
    build:
      dockerfile: src/TempusHub.Web/Dockerfile
      context: .
    image: tempus-hub
    container_name: tempus-hub
    ports:
      - "9001:80"
    restart: always
    env_file:
      - env-vars.env